### ISSUE TITLE
Linux (and possibly *nix) build

### ISSUE THREAD

**Issue by hidden-r4d** [GalaxzyDev/Deadcord#19]
Is it possible to (easily) release a Linux ( and/or *nix) build of this project?

**Comment by Galaxzy345** [comment]
Yes, we are releasing a Golang cross compatible rewrite of Deadcord in the upcoming week. I would suggest joining our subreddit for news as well

**Comment by hidden-r4d** [comment]
Great news, glad to hear it, I'll close this when it's confirmed working.

**Comment by GalaxzyDev** [comment]
Yep, that's what I planned on, can you confirm it is working?

**Comment by hidden-r4d** [comment]
> Yep, that's what I planned on, can you confirm it is working?

I can't confirm it working just yet, because I don't have the plugin. However, it seems to be running perfectly fine.

**Comment by hidden-r4d** [comment]
Working (at the very least) partially on Ubuntu 20.04. Closing.
