### ISSUE TITLE
CMD raid tool

### ISSUE THREAD

**Issue by lgamerlive** [GalaxzyDev/Deadcord#21]
Can you make it so you can also atack from the dead cord application? That will help me, cuz betterdiscord refuses to install.

**Comment by ayunami2000** [comment]
Though I wont be using this, I can also confirm betterdiscord does not install for me either...

**Comment by JamesJamesonJo** [comment]
LOVE this tool. Just wondering if there will be captcha solver options added to integrate with some captcha solving APIs. Seems every time I try to join a channel with a token there's a cap to solve. Thanks

**Comment by GalaxzyDev** [comment]
Thank you for your support in this project, I plan on adding a captcha solver or solving service in the near future, just been taking a break from development for a bit. Discord is changing the ways tokens work, so I am preparing for that as well.
