### ISSUE TITLE
doesnt join servers

### ISSUE THREAD

**Issue by atxmicoffxan** [GalaxzyDev/Deadcord#23]
i dont know if im just doing it wrong or what i followed all the steps and it doesnt join or anything

**Comment by GalaxzyDev** [comment]
Did you provide the full invite URL? Is the engine running in the background? What does the terminal window show?

**Comment by atxmicoffxan** [comment]
ay dude my fault it was the tokens

**Comment by GalaxzyDev** [comment]
I'm reopening this temporarily to let you know there will be an update very soon that will improve joining.
