### ISSUE TITLE
Runtime Error When Joining Guild

### ISSUE THREAD

**Issue by Noliwankenobi** [GalaxzyDev/Deadcord#30]
On attempt to join guild:

``http: panic serving [::1]:1025: runtime error: index out of range [3] with length 1
goroutine 22 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1825 +0xbf
panic({0x11f68c0, 0xc00030c078})
        C:/Program Files/Go/src/runtime/panic.go:844 +0x258
Deadcord/modules.GetGuildIdAndChannelIdFromInvite({0xc000320097?, 0x1?})
        C:/Users/user/Desktop/Deadcord-main/modules/Helpers.go:37 +0x245
main.join_guild({0x12b0120?, 0xc00033a0e0}, 0xc000326300)
        C:/Users/user/Desktop/Deadcord-main/main.go:242 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc000326200?, {0x12b0120?, 0xc00033a0e0?}, 0x0?)
        C:/Program Files/Go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002fa000, {0x12b0120, 0xc00033a0e0}, 0xc000326100)
        C:/Users/user/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x12af488?}, {0x12b0120, 0xc00033a0e0}, 0xc000326100)
        C:/Program Files/Go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00051e6e0, {0x12b0318, 0xc000089d10})
        C:/Program Files/Go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        C:/Program Files/Go/src/net/http/server.go:3071 +0x4db``

**Comment by GalaxzyDev** [comment]
I have fixed this issue, use the full invite (https://discord.gg/invite/code) until I push an update.
